version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Docker.backend
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  frontend:
    build:
      context: .
      dockerfile: Docker.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
